#!/bin/bash

GRAPHHOPPER="3rd_party/graphhopper-0.1.jar"
SWING="/usr/share/java/scala-swing.jar"
JFREECHART="3rd_party/jfreechart-1.0.14.jar:3rd_party/jcommon-1.0.17.jar"

CLASSPATH=".build:$GRAPHHOPPER"
#TEST_MEM="-J-verbosegc"
TEST_MEM=""
JVM_OPTS="-J-Xmx1536m $TEST_MEM"
FULL_CP="$GRAPHHOPPER:$SWING:$JFREECHART"
