#!/bin/bash

. common

SRCS=`find utexas/ -name '*.scala' -print | xargs`
BUILD_OPTS="-d .build -Sdeprecation -Sunchecked -Sfeature -cp $FULL_CP"
FAST=""
COMPILER="scalac"
COMPILER="/home/dabreegster/zinc/bin/zinc -scala-home /usr/share/scala -nailed"
#FAST="-Xelide-below 3000"   # disables asserts, timers, and stats

echo Compiling...
mkdir -p .build
$COMPILER $BUILD_OPTS $FAST $SRCS

# How did the compile go?
if [[ $? != "0" ]]; then
  exit 1
fi
