#!/bin/bash

SRCS=`ls map/*.scala map/make/*.scala ui/*.scala`
SWING="/usr/share/java/scala-swing.jar"
# TODO switch to ant, damnit.
BUILD_OPTS="-d .build -deprecation -cp $SWING"
RUN_OPTS="-cp .build:$SWING"                 # TODO memory?

if [[ $1 ]]; then
  cmd=$1
else
  cmd="b"
fi

fsc $BUILD_OPTS $SRCS

# How did the compile go?
if [[ $? != "0" ]]; then
  exit 1
fi

echo

case $cmd in
  a)
    scala $RUN_OPTS map.make.Builder $2 $3
    ;;
  b)
    scala $RUN_OPTS ui.Viewer $2
    ;;
  *)
    echo "Unknown command $cmd"
    echo "Usage:"
    echo "./run a [foo.osm] [gps]   - pre-process a new OSM map"
    echo "./run b                   - simulate a map"
    ;;
esac
