#!/bin/bash
# Must be run from the base AORTA directory, eg,
# ./tools/analyze_routes

. common

scala -cp $CLASSPATH $JVM_OPTS utexas.aorta.analysis.RouteAnalyzer $@
#scala -cp $CLASSPATH $JVM_OPTS utexas.aorta.analysis.DifferentialRouteAnalyzer $@
