#!/bin/bash
# Must be run from the base AORTA directory, eg,
# ./tools/analyze_externality

. common

scala -cp $CLASSPATH $JVM_OPTS utexas.aorta.analysis.ExternalityAnalyzer scenarios/austin_externality 30000 $@
