#!/bin/bash
# Must be run from the base AORTA directory, eg,
# ./tools/finalize big_btr-equal

NAME=$1
DIR="final"

if [[ -z $NAME ]]; then
  echo "Usage: ./tools/finalize big_btr-equal"
  exit
fi

BASE="${DIR}/${NAME}"
mkdir -p $BASE

./analyze logs/$NAME > ${BASE}/summary
cp scenarios/$NAME ${BASE}/scenario
cp logs/$NAME ${BASE}/log
cp plots/$NAME/* ${BASE}/
