#!/bin/bash
# Must be run from the base AORTA directory, eg,
# ./tools/run big_btr-equal

NAME=$1
SECONDS=`expr 5 \* 3600`
LIMIT="--time_limit ${SECONDS}"

if [[ -z $NAME ]]; then
  echo "Usage: ./tools/run big_btr-equal"
  exit
fi

./headless scenarios/${NAME} --log logs/${NAME} ${LIMIT}
