#!/bin/bash
# Must be run from the base AORTA directory, eg,
# ./tools/run big_btr-equal

NAME=$1

if [[ -z $NAME ]]; then
  echo "Usage: ./tools/run big_btr-equal"
  exit
fi

./headless scenarios/${NAME} --log logs/${NAME}
